### PR TITLE
Updating deprecated functions

### PR DESCRIPTION
**Pull request by dhensby**
See https://github.com/silverstripe/silverstripe-framework/pull/3799

### CODE REVIEW

**Comment by dhensby** [comment]
@chillu any ideas on the behat errors?

**Comment by tractorcow** [comment]
@dhensby did you mean to merge this into master? I don't think we were changing the api for those methods in 3.2.

**Comment by tractorcow** [comment]
I've restarted this build not sure what's going on.

**Comment by chillu** [comment]
The build was broken because there was a pretty obvious fatal error when opening `admin/assets` - easy to reproduce locally based on the Behat output, although it would be nicer to have seen it in a screenshot. For some reason the travis build tooling has lost the AWS key config, so is no longer uploading screenshots to S3.

**Comment by kinglozzer** [comment]
> pretty obvious fatal error when opening `admin/assets`



Thanks @chillu

**Comment by dhensby** [comment]
@chillu I think secure env variables aren't available to PRs / forks...

**Pull request merged**
