### PR TITLE
PATCH: change "with No Content" to "without content" in reports

### PR DESCRIPTION
**Pull request by sunnysideup**

### CODE REVIEW

**Comment by sunnysideup** [comment]
I checked the dutch translation.

The dutch translation said: "zonder" - which is translated to "without". 

Also, "with no" is basically bad English for "without" so I don't really see your point - i.e. if the translations were bad in the first place then they will not get worse by changing the English to better English?

**Comment by sunnysideup** [comment]
i  am happy to check Spanish / German / French the the reo if the helps?

**Comment by robbieaverill** [comment]
Thanks for checking. In this case it’s probably not an issue, but usually we don’t change translation source (English) definitions, because people have translated “with no” rather than “without” when may then invalidate the translated versions. I presume it’ll be fine in this case because it’s a minor adjustment.

**Comment by sunnysideup** [comment]
Totally agree.

**Comment by robbieaverill** [comment]
Would you mind updating the failed behat test copy too?

**Comment by sunnysideup** [comment]
Done

**Comment by robbieaverill** [comment]
cc @silverstripeux - if you’re happy here feel free to merge

**Pull request merged**
