### PR TITLE
API Better behaviour for virtualised controller

### PR DESCRIPTION
**Pull request by tractorcow**
Dependency of https://github.com/silverstripe/silverstripe-cms/issues/1572

Cleans up some inconsistent controller bootstrapping in virtual page controller.

### CODE REVIEW

**Comment by tractorcow** [comment]
@dhensby could you please review this? :P

**Comment by hafriedlander** [comment]
Nice cleanup.

**Comment by tractorcow** [comment]
Yay thanks @hafriedlander

**Comment by dhensby** [comment]
Sorry, I was on holiday!

**Pull request merged**
