### PR TITLE
SS5: Remove trailing slash from SiteTree links if no action present

### PR DESCRIPTION
**Pull request by xini**
This change helps normalising and canonicalisation of URLs. This picks up https://github.com/silverstripe/silverstripe-cms/pull/2631 again for SS5.

`SiteTree::RelativeLink()` is currently the only place in SS where a trailing slash is added to a URL when there is no `$action` parameter given.

`Controller::join_links()` already adds slashes between sections of the path, the explicit slash in `RelativeLink()` is not needed.

Classes that don't use `Controller::join_links()` at all, e.g. https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/PaginatedList.php#L446-L453 use the current request, which never has a trailing slash.

## Parent issue
- #2780

### CODE REVIEW

**Comment by GuySartorelli** [comment]
@xini We've added some acceptance criteria to https://github.com/silverstripe/silverstripe-cms/issues/2780
Can you please modify this PR to meet those acceptance criteria?

**Comment by GuySartorelli** [comment]
Rebased, added necessary JS changes, and squashed commits.
Note that this PR will need to be modified once https://github.com/silverstripe/webpack-config/pull/57 has been merged and released in NPM.

**Comment by GuySartorelli** [comment]
webpack-config changes are now included in this PR

**Review by emteknetnz — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Failing JS tests are going to be dealt with in https://github.com/silverstripe/silverstripe-admin/issues/1421

**Pull request merged**
