### PR TITLE
Removing stage reading mode as it will be set in LeftAndMain

### PR DESCRIPTION
**Pull request by dhensby**
This depends on https://github.com/silverstripe/silverstripe-framework/pull/5005

### CODE REVIEW

**Comment by tractorcow** [comment]
Restarting tests; Will merge later.

It won't hurt to leave this in for the mean time. :D

**Comment by dhensby** [comment]
right... no idea why this wouldn't be working

**Comment by dhensby** [comment]
Hmmmm I'm getting these errors locally :/ that's not good...

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/5005/files.

Your framework PR was wrong sorry. :)

**Comment by tractorcow** [comment]
I was going to restart that. :P

**Pull request merged**
