### PR TITLE
Behat test cases for site tree duplication

### PR DESCRIPTION
**Pull request by tractorcow**
Test cases for https://github.com/silverstripe/silverstripe-framework/pull/3031

Do not merge before the above, because these fixtures rely on extensions to behat in the above PR.

### CODE REVIEW

**Comment by dhensby** [comment]
COME ON @tractorcow LET'S GET THIS SHOW ON THE ROAD

**Comment by tractorcow** [comment]
Uh... I don't even remember writing these tests. Maybe it was a different @tractorcow?

**Comment by SpiritLevel** [comment]
Body snatchers....I knew it!

**Comment by sminnee** [comment]
I've re-triggered the build on this.

**Pull request merged**
