### PR TITLE
sanitize namespaced classes for page icon css

### LINKED ISSUE #980: SiteTree icon doesn't work when using namespaced classes
SiteTree icon doesn´t work when using namespaced classes. I guess, the issue is that the css won't work with css class names containing backslashes.

Copied from silverstripe/silverstripe-framework#2980

(cc @bumbus)

### PR DESCRIPTION
**Pull request by andrewandante**
Fixes #980

### CODE REVIEW

**Comment by dhensby** [comment]
How do you feel about back-porting this fix to 3.5 as this issue was originally reported against 3.1!

**Comment by andrewandante** [comment]
Will see what I can do

**Comment by flamerohr** [comment]
he fixed the treedropdown, add page and list view icons :D
such a champion

**Comment by andrewandante** [comment]
3.5 Backport added @dhensby

**Pull request merged**
