### PR TITLE
Fixes relating to Controller cleanup

### PR DESCRIPTION
**Pull request by dhensby**
Depends on https://github.com/silverstripe/silverstripe-framework/pull/3926

### CODE REVIEW

**Comment by dhensby** [comment]
Need to find a way to deal with the code duplication in RootURLController/ModelAsController

**Comment by dhensby** [comment]
rebased

**Comment by tractorcow** [comment]
Now that framework is merged, I'll restart these tests and wait for it to pass.

**Comment by tractorcow** [comment]
Sorry @dhensby your tests aren't passing. https://travis-ci.org/silverstripe/silverstripe-cms/jobs/132155179

Can you please fix?

**Comment by tractorcow** [comment]
I've merged it in with a tiny fix. ;D

**Comment by dhensby** [comment]
<3

**Pull request merged**
