### PR TITLE
Fixes #944: More Robust wait for text

### PR DESCRIPTION
**Pull request by srizzling**
This PR is reliant on https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/57 being merged.

### CODE REVIEW

**Comment by srizzling** [comment]
No idea what this means anymore :(

**Comment by tractorcow** [comment]
Sorry it's been a long time. :D

**Comment by srizzling** [comment]
Heh, might have my one year anniversary :D

**Comment by dhensby** [comment]
Do we not want this change in? Waiting for an element is better than arbitrary time...

**Comment by dhensby** [comment]
Does need recasting, though :(

**Comment by srizzling** [comment]
I just forgot how it works. I can rebase if you wish.

**Comment by dhensby** [comment]
Please do

**Comment by chillu** [comment]
Stale PR, closing

**Comment by tractorcow** [comment]
Oh, this is fixed in new behat3 anyway, albeit in a different way. @chillu go to bed. :D

**Pull request closed without merging**
