### PR TITLE
Use setFailover() in ContentController (closes silverstripe/silverstripe-framework#4821)

### PR DESCRIPTION
**Pull request by kinglozzer**
Depends on https://github.com/silverstripe/silverstripe-framework/pull/4870.

### CODE REVIEW

**Comment by tractorcow** [comment]
I've merged the other PR and restarted the tests. Please get back to me when this is ready to merge. :)

**Comment by kinglozzer** [comment]
Ping @tractorcow :)

**Comment by tractorcow** [comment]
Thanks :D

**Comment by dhensby** [comment]
I've just installed 3.x-dev and I'm getting:

```
ERROR [User Error]: Uncaught Exception: Object->__call(): the method 'setfailover' does not exist on 'ContentController'
IN POST /admin/pages/edit/EditForm
Line 740 in /vagrant/www/framework/core/Object.php
```

I think `setFailover` is only defined on `ViewableData` and not `Controller` so this will break - not sure why it's not causing tests to fail though...

This is just plain 3.x-dev install

**Comment by tractorcow** [comment]
I just did a merge up from 3.2 -> 3.3 -> 3... must be related?

**Comment by tractorcow** [comment]
> I think setFailover is only defined on ViewableData and not Controller so this will break - not sure why it's not causing tests to fail though...

But ViewableData is a parent class of Controller, so that can't be the cause. :P

**Comment by dhensby** [comment]
I probably typoed in the composer requirements and took in something bad. it's all ok now!

**Pull request merged**
