### PR TITLE
Update class namespace for campaign admin

### PR DESCRIPTION
**Pull request by tractorcow**
See https://github.com/silverstripe/silverstripe-framework/issues/6735

### CODE REVIEW

**Comment by sminnee** [comment]
@tractorcow now that we've merged versioned, does this need a rebase?

**Comment by tractorcow** [comment]
Rebased.

**Comment by chillu** [comment]
Given the `cms` module depends on campaign admin functionality, should they require it in `composer.json`? e.g. for `AddToCampaignHandler`

**Comment by chillu** [comment]
Damian agrees that we need that dependency, so I've added it here.

**Pull request merged**
