### PR TITLE
API respect custom attributes on OptionsetField and CheckboxSetField

### PR DESCRIPTION
**Pull request by tractorcow**
Must be merged with https://github.com/silverstripe/silverstripe-framework/pull/4390

### CODE REVIEW

**Comment by dhensby** [comment]
Seriously, using IDs like this really makes me sad :(

**Comment by tractorcow** [comment]
Whoops, this needed to be merged with that other PR @dhensby :D This is why cms tests are failing now.

**Comment by tractorcow** [comment]
Rebased and squashed.

**Comment by tractorcow** [comment]
Well the add-page dialog is fixed, but there's another issue still to resolve.

**Comment by tractorcow** [comment]
It turned out that `CORE_RELEASE=3` on 3.2 is not a good thing.

**Comment by tractorcow** [comment]
Also found out that recent regressions broke the insert-file dialog.

**Pull request merged**
