### PR TITLE
Set locale on datefields from current user

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-admin/issues/631

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Nice branch name. Is that the right base issue? 

I sort of feel like DateFields should use the current users locale by default.

**Comment by unclecheese** [comment]
Yeah, I thought about that, but I think it's too much coupling. A better long-term fix would be to have the locale fallback on a setting, so that somewhere upstream we could just set `DateField::set_default_locale($currentUser->Locale)`, but that seems a bit too impactful given that this is for a story unrelated to DateField. Probably worth raising an issue.

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/8339

**Comment by unclecheese** [comment]
Actually on second look, this should be falling back to i18n::get_locale(), which is set in LeftAndMain::init(). This could be an issue isolated to our behat test.

**Comment by robbieaverill** [comment]
I restarted Behat and it went green

**Pull request merged**
