### PR TITLE
API Rescue Master Branch PR: Remove deprecated CMSPageHistoryViewer

### PR DESCRIPTION
**Pull request by GuySartorelli**
Rescues https://github.com/silverstripe/silverstripe-cms/commit/cb737aa842a3b980c709e564d98846c1cf4310e6

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10350

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Did a quick smoke test, compared 2 page versions, it works OK

There's still what looks like some dead (or just buggy) code around in core e.g. `HistoryControllerFactory` which has `return new CMSPageHistoryController();` - try searching for `CMSPageHistoryController`

Should remove that code as well.

**Comment by GuySartorelli** [comment]
Code in silverstripe/versioned-admin (which is where `HistoryControllerFactory` lives) cannot be removed in this PR. I will create a new PR to remove that, but it should not hold up this PR from being merged.

edit: The new PR: https://github.com/silverstripe/silverstripe-versioned-admin/pull/251

**Comment by GuySartorelli** [comment]
I have added a new commit to remove the css for the history controller.

**Comment by GuySartorelli** [comment]
Needs https://github.com/silverstripe/silverstripe-asset-admin/pull/1290 and https://github.com/silverstripe/silverstripe-postgresql/pull/135 to be merged for CI to go green.

**Comment by emteknetnz** [comment]
Both other PRs have been merged, rerunning tests

**Comment by GuySartorelli** [comment]
The current CI failure will be resolved when https://github.com/silverstripe/silverstripe-framework/pull/10479 is merged (though there will likely be others after that)

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
