### PR TITLE
remove trailing spaces in the codebase

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow do we want these kinds of things in master?

**Comment by tractorcow** [comment]
Yes please; Merging up 3 -> master is becoming tricky. Please can you re-open this pull request on master?

**Comment by spekulatius** [comment]
Sure, I'll do.

**Comment by spekulatius** [comment]
@tractorcow I reopened this pointing at master: https://github.com/silverstripe/silverstripe-cms/pull/1286

**Pull request closed without merging**
