### PR TITLE
Add dependency on admin module

### PR DESCRIPTION
**Pull request by tractorcow**
Requires https://github.com/silverstripe/silverstripe-framework/pull/6695

We had to move CMSPreviewable to framework module, as otherwise framework classes couldn't inherit it without directly requiring admin module (undesirable).

### CODE REVIEW

**Comment by dhensby** [comment]
> We had to move CMSPreviewable to framework module, as otherwise framework classes couldn't inherit it without directly requiring admin module (undesirable).

this sounds bad, surely all of those classes should then be moved to the admin module? which classes are they?

**Comment by tractorcow** [comment]
Because otherwise we'd need admin to be a dependency of framework, which is a more annoying coupling.

**Comment by dhensby** [comment]
> Because otherwise we'd need admin to be a dependency of framework, which is a more annoying coupling.

why?

**Comment by tractorcow** [comment]
Sorry I modified my comment. :)

**Comment by dhensby** [comment]
hmm... ok :/

**Pull request merged**
