### PR TITLE
Refactor ErrorPage to have static file building in a separate method

### PR DESCRIPTION
**Pull request by ss23**
Also changes to file_put_contents and single quotes for readability in some places

### CODE REVIEW

**Comment by ss23** [comment]
scrutinizer error wasn't me pls merge

**Comment by chillu** [comment]
Why is that necessary? 

BTW there's some discussion around removing the `ErrorPage` class from core on the mailinglist (for 4.x): https://groups.google.com/forum/#!topic/silverstripe-dev/VFXrusjAnKE

**Comment by ss23** [comment]
When doing static publishing, the base URL is different, I need to re-trigger this particular function when the static publisher is called. This is the easiest way I can think of doing it.

With that in mind, it may need to be public, not protected... any objections to merging if I make it public?

**Comment by chillu** [comment]
Good enough of a reason :) Changed to public and pushed as 857ade7d1d37c360cfc1f78cfe7c68a817343f92

**Pull request closed without merging**
