### PR TITLE
Fix linking anchor on the same page

### PR DESCRIPTION
**Pull request by wilr**
To reproduce this issue open a page, add an anchor, save the page, attempt to link to newly created anchor on the same page.

Previous incorrect result will be the new anchor does not appear in the list as the list is not refetched off the server. This patch ensures that the page anchors are reloaded.

### CODE REVIEW

**Comment by robbieaverill** [comment]
The test failure is valid

**Comment by wilr** [comment]
@robbieaverill  Is the test valid though? Why would you load the anchors without  pageId?

**Comment by wilr** [comment]
Ah sorry yep I see what the purpose was for that test. I've updated the code to achieve what the test meant.

**Comment by ScopeyNZ** [comment]
Thanks @wilr. Can you make sure you're committing the bundle as well?

**Comment by wilr** [comment]
@ScopeyNZ I get this while trying to build (not watch) ```ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "silverstripe/admin/package.json" at 0, attempted to resolve relative to "silverstripe/admin"```

**Comment by ScopeyNZ** [comment]
You will probably need to `yarn` in admin too. Also it looks like a rebase is needed.

I'll fix it up for you. As this is a bugfix did you want to target the next patch release instead of the next minor?

**Comment by ScopeyNZ** [comment]
There you go - all fixed up and targetted at the next patch 🙂

**Comment by ScopeyNZ** [comment]
Closing/re-opening to get travis working correctly

**Pull request merged**
