### PR TITLE
MINOR Change how OldPageRedirector gets URLs to fix nested redirects

### PR DESCRIPTION
**Pull request by ss23**
Previously, we would be limited by the way allParams will return 3 parameters at most. This way, we get the full URL.
Keep in mind, this code still needs a clean up, but at least it's not buggy now.

This should probably be merged up as required.

### CODE REVIEW

**Comment by sminnee** [comment]
Test looks like it covers it, and it's a bug so good for 3.1.

**Comment by ss23** [comment]
I tried bouncing travis but it's not working. The old travis run had a failure on behat that looked unrelated (couldn't select ErrorPage). Is it overloaded or something, or can we just merge or what? :O

**Comment by sminnee** [comment]
Bounced the behat build, it works.

**Comment by sminnee** [comment]
But no, I wouldn't merge until I'd seen a green tick. Either bouncing the build will fix it or it's something that would risk introducing a failure to the main branch, which would suck.

**Pull request merged**
