### PR TITLE
BUGFIX: Move AnchorSelectorField to admin

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-framework/issues/7996

### CODE REVIEW

**Comment by unclecheese** [comment]
Behat test is failing because of dependency on the `silverstripe/admin` PR.

**Comment by tractorcow** [comment]
You're only moving the js not the php backend AnchorSelectorField.php.

**Comment by tractorcow** [comment]
See my comment at https://app.zenhub.com/workspace/o/silverstripe/silverstripe-framework/issues/7996#issuecomment-395295048. I dislike this approach.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-cms/pull/2182 for alternative solution.

**Comment by robbieaverill** [comment]
The original issue was closed with an alternative solution

**Pull request closed without merging**
