### PR TITLE
VirtualPage call init on target controller

### PR DESCRIPTION
**Pull request by stnvh**
Fixes [#1099](https://github.com/silverstripe/silverstripe-cms/issues/1099)

### CODE REVIEW

**Comment by wilr** [comment]
e2d85b2f88193a356311eb7b433710d6342c9273

**Comment by dhensby** [comment]
@wilr this is a bug fix, so should make it's way into 3.1? I suggest this gets merged

**Comment by wilr** [comment]
I'm an api change too

**Comment by dhensby** [comment]
Hmm? It's not an api change that I see? Definitely count it as a bug fix myself

**Comment by chillu** [comment]
I agree its an API change - init() typically has side effects, e.g. `Requirements` inclusion. That's likely desired in most cases, but not all of them - so should go against 4.0

**Comment by dhensby** [comment]
Ok

**Pull request closed without merging**
