### PR TITLE
BUGFIX: Broken "show as list"

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-cms/issues/2210

### CODE REVIEW

**Comment by maxime-rainville** [comment]
@unclecheese I'm getting some weird behavior when interacting with the SiteTree List view. 
https://youtu.be/aLP4Nz1dTaY

When I revert to using the 4 branch everything works fine aside from the _Show List_ link.

**Comment by unclecheese** [comment]
Good testing, @maxime-rainville. I've made some updates to fix that bug. Also, please see the other [minor PR to admin](https://github.com/silverstripe/silverstripe-admin/pull/588) to fix the spacing on that link.

**Comment by unclecheese** [comment]
Fixed the first bug. The second one is much more complicated. This is a major UI regression, and from what I can tell, this feature was just never supported in SS4, and many of the required pieces to get it working are simply missing, (e.g. passing parent node and view state through the URL).

Will check in with @chillu  on this one.

**Comment by unclecheese** [comment]
Alright, that should do it. Ready for another test, @maxime-rainville

**Comment by unclecheese** [comment]
Alright, that will do it.

**Comment by maxime-rainville** [comment]
This work was cherry picked into an older branch in https://github.com/silverstripe/silverstripe-cms/pull/2232.

**Pull request closed without merging**
