### PR TITLE
Fixing issue #2522

### PR DESCRIPTION
**Pull request by t3hn0**
Pull request fixin issue #2522

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Thanks for the PR. I think this would read cleaner if you combined this filter with the prior filter:

```php
$pages = SiteTree::get()->filter([
    'URLSegment' => $URL,
    'Parent' => $parent ? $parent->ID : 0,
]);
```

Then you can remove that whole `if...else` block.

In saying that, looks like you've got a valid test failure caused by this PR. I can't provide any insight on that sorry.

**Comment by t3hn0** [comment]
Thanks I can fix that but somebody should check what the error is since it's the same logic and would still cause same error :)

**Comment by ScopeyNZ** [comment]
You can still optimise further but combining those two `->filter` calls together.

The builds on `4` are fine, so this logic change _is_ causing a test failure. I'm sorry, but I don't have time to look at it now. Perhaps look at the assertion it's trying to make (if you haven't already) - it could give you clues as to why this patch might have affected it.

**Comment by t3hn0** [comment]
Sorry just added quick fix...I made it propper now.

I reviewed the test and the problem is in this test
ModelAsControllerTest::testRedirectionForPreNestedurlsBookmarks

This test tests if URL` /newlevel3` should be found at `/newlevel1/newlevel2/newlevel3/`. My PR surely disables this with condition of ParentID=0 if no $parent is set.

I'm not sure how and if this is important to work..you'll decide. But other way of fixing reported error would be if $parent would somehow be transfered to OldPageRedirector::onBeforeHTTPError404() function in RequestHandler::httpError.

**Comment by Cheddam** [comment]
Right, so the issue is that the existing logic was actually supporting cases where a page changed nesting level (e.g. went from being a top-level page to being a child page).

Perhaps a good trade-off would be to prioritise the new behaviour (searching with ParentID = 0), and then fall back to the old behaviour in order to find any matches that would have occurred before. It's two queries instead of one (although you could optimise the second query away), but seems worthwhile to get the best of both worlds.

Thoughts @ScopeyNZ?

**Comment by ScopeyNZ** [comment]
I trust your judgement. Seems like the second query would be uncommon anyway.

**Comment by t3hn0** [comment]
Hi @Cheddam 

I've reverted all the chages I made so far and updated code as you suggested and now all test pass.

**Comment by Cheddam** [comment]
@t3hn0 Awesome! Before we give it a final tick and merge, could you squash the commits together and give the combined commit a formatted message like `BUG Prioritise same-level pages in OldPageRedirector`? See [the commit message docs](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages) for more detail.

**Comment by t3hn0** [comment]
@Cheddam great. Should I create new PR with single commit than and close this one?

**Comment by Cheddam** [comment]
Up to you - you could rebase the current branch and force push it, though, to save creating a separate PR.

I've noticed that you've created this pull request from one of the "core branches" (`4`) rather than a branch specifically intended for this pull request. This would cause problems if we asked you to target this PR at a different branch. No action is needed, this is for your information.

In the future please create a new branch for each individual pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request).

**Comment by t3hn0** [comment]
@Cheddam thanks for the tip & for links to docs. I managed to squash commits and I updated commit message.

**Pull request merged**
