### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by torleif**
[Fix] dead links for 3.1

### CODE REVIEW

**Comment by chillu** [comment]
@cam-findlay @wilr Do you know why those links have been broken? Do we need a redirect from trunk/master to 4.0? :(

**Comment by camfindlay** [comment]
@ingo there should be a rewrite for trunk however I'm finding the rewrites from a while back didn't include a /?$ at the end of the incoming link so in some cases non-trailing slash links haven't been matching. There is some work going on over in docs repo on the rewrites at the moment by a community member with some mentoring from me so hopefully we can clean many of these up.

**Comment by jonom** [comment]
Looks like /contributing used to be nested under /misc but isn't anymore?

Might be a silly question but shouldn't the contents of this file be in the README.md file? Much better chance of people reading it there I would have thought.

**Comment by camfindlay** [comment]
@jonom the CONTRIBUTING file is a GitHub standard.

**Comment by jonom** [comment]
Ohhh. Cool. :+1:

**Pull request merged**
