### PR TITLE
NEW Change "only these people" to "only these groups" in permissions

### LINKED ISSUE #1873: Page permissions minor text change
Just a simple text change from "people" to "groups" to make the field clearer.
pasted_image_28_06_17__4_13_pm

### PR DESCRIPTION
**Pull request by robbieaverill**
Issue: #1873 

Other PR: https://github.com/silverstripe/silverstripe-siteconfig/issues/67

### CODE REVIEW

**Comment by dhensby** [comment]
behat failed - I'm restarting just in case it's bad luck but it was related to permission settings. perhaps behat tests are tightly coupled to the default translation.

**Comment by dhensby** [comment]
still failing :(

**Comment by robbieaverill** [comment]
I was seeing locally earlier that composer was having trouble installing the framework at `4.0.x-dev` - assumed related to the new branch creation. Looks like this Travis job is having the same problem (dying silently though?)

**Comment by dhensby** [comment]
seems to be installing fine? (https://travis-ci.org/silverstripe/silverstripe-cms/jobs/249561975#L348)

**Comment by robbieaverill** [comment]
Ha, yeah. Think my browser had a tanty.

**Comment by robbieaverill** [comment]
@flamerohr de-nied?

**Comment by kinglozzer** [comment]
@robbieaverill Nah, the 4.0 branch was deleted so it got auto-closed, you should be able to re-open it if you change the target branch first 😄

**Comment by robbieaverill** [comment]
Oh! That'll do it!

**Comment by robbieaverill** [comment]
I can't reopen it - will open a new one

**Comment by kinglozzer** [comment]
howbowdah?

**Comment by robbieaverill** [comment]
You have the mad powerz

**Comment by robbieaverill** [comment]
Weird that behat is still failing. @tractorcow do you know why this might behatppening?

**Comment by flamerohr** [comment]
apologies @robbieaverill I was half way through cleaning up the branches and composer settings then I had to rush off to an emergency

**Comment by robbieaverill** [comment]
No stress @flamerohr

**Comment by robbieaverill** [comment]
Ok turns out the failure was real, there's an identical set of dropdowns in siteconfig (PR at https://github.com/silverstripe/silverstripe-siteconfig/issues/67) which is what was being tested in behat rather than the page edit permissions.

**Comment by robbieaverill** [comment]
I'll remove the settings area tests which have now been moved to the siteconfig module and re-write them for page edit settings - which should mean that this PR can be merged.

It looks like https://github.com/silverstripe/silverstripe-siteconfig/pull/67 is still failing behat, which I suspect is because the CMS translation for "only these people" hasn't been updated, and is taking precedence during the siteconfig behat builds.

If this PR is merged happily on its own then that PR's build can be restarted and should pass.

**Comment by robbieaverill** [comment]
Behat tests updated for page specific edit permissions - I've left a test that should pass but currently doesn't because of https://github.com/silverstripe/silverstripe-cms/issues/1897 commented out

**Pull request merged**
