### PR TITLE
Add page layout based on Bootstrap markup

### PR DESCRIPTION
**Pull request by clarkepaul**
I've simplified the steps styles but added additional responsiveness. It does look a bit different from what we had, and could probably be improved still but this should satisfy the issue of the layout being broken.

Requires https://github.com/silverstripe/silverstripe-framework/pull/5697 merged first.
Requires https://github.com/silverstripe/silverstripe-framework/pull/5728
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1526

Result:
pasted_image_22_06_16__7_12_pm

### CODE REVIEW

**Comment by clarkepaul** [comment]
Added styling to breadcrumb.
Moved notice to top.
pasted_image_23_06_16__10_28_am

**Comment by clarkepaul** [comment]
Found some issues with the Javascript applied to the page, disabling of item if not allowed etc. Don't merge yet.

**Comment by clarkepaul** [comment]
Can't seem to figure it out so will need a bit of dev help here. On step 1 when you select something from the tree dropdown it should do a check to see if the available children are allowed (which it isn't doing).

**Comment by tractorcow** [comment]
I'm peer reviewing and manually merging this.

**Comment by clarkepaul** [comment]
I've cleaned up this work and replacing it with https://github.com/silverstripe/silverstripe-cms/pull/1554

**Pull request closed without merging**
