### PR TITLE
API Support new DataObject::can() signature

### PR DESCRIPTION
**Pull request by tractorcow**
Required for https://github.com/silverstripe/silverstripe-framework/pull/5247

### CODE REVIEW

**Comment by hafriedlander** [comment]
Bunch of behat test failures. I'll have a look in the morning.

**Comment by chillu** [comment]
I've fixed CMS loading by cherry picking the `SiteTree->can()` change in the meantime: 5a7b708

**Comment by tractorcow** [comment]
Fixes for travis artifacts are here https://github.com/silverstripe-labs/silverstripe-travis-support/pull/31

Then that will help debug the issues in this PR.

**Comment by tractorcow** [comment]
Tests fixed by https://github.com/silverstripe/silverstripe-framework/pull/5273

**Comment by tractorcow** [comment]
Green ticks!

**Pull request merged**
