### PR TITLE
Fixes pages not being scrolled to on treeview

### PR DESCRIPTION
**Pull request by bergice**
Resolves https://github.com/silverstripe/silverstripe-cms/issues/1511

### CODE REVIEW

**Comment by bergice** [comment]
Resolves https://github.com/silverstripe/silverstripe-cms/issues/1511

**Review by emteknetnz — CHANGES_REQUESTED** [review]
This is definitely a big improvement from the current behaviour

One thing we could improve is to add "one-row" of padding at the top so that the selected page is not at the very top.  With this PR it will scroll to here:

image

I think it might be nicer if it scrolled to here instead

image

Alternatively, maybe it would make sense for to be "one from the bottom"
image

@sachajudd what's your view?

**Comment by sachajudd** [comment]
Near the top makes more sense than at the bottom e.g if you're opening up a page with children pages it'd be a hassle to keep scrolling after the first initial scroll. Not fussed either way where the selected page lands. Looks good either way nice work @bergice

**Comment by emteknetnz** [comment]
@sachajudd great ta.  So at the top with or without "one row" of padding?

**Comment by bergice** [comment]
@emteknetnz it should select the previous list item now.

**Review by maxime-rainville — APPROVED** [review]
Works well tested in IE11, Firefox and Chrome.

**Pull request merged**
