### PR TITLE
"npm run lock" command

### PR DESCRIPTION
**Pull request by chillu**
Uses https://github.com/uber/npm-shrinkwrap instead of the built-in "npm shrinkwrap" since it works more reliably.
Specifically, "npm install" doesn't fail depending on node_modules/ being installed in the local cache or not.
It also makes npm-shrinkwrap.json easier to diff by more consistently ordering its output between runs.

If you need any convincing that this is a problem, look at the over 400 issues related to "shrinkwrap"
in https://github.com/npm/npm/search?q=shrinkwrap&type=Issues&utf8=%E2%9C%93

Requires https://github.com/silverstripe/silverstripe-framework/pull/5106

/cc @flashbackzoo

### CODE REVIEW

**Comment by flashbackzoo** [comment]
Nice. I see you remembered to shrinkwrap npm-shrinkwrap too :smile:

**Comment by chillu** [comment]
Builds will pass once https://github.com/silverstripe/silverstripe-framework/pull/5087 is resolved

**Comment by dhensby** [comment]
Still not passing @chillu

**Comment by chillu** [comment]
Committed through https://github.com/silverstripe/silverstripe-cms/commit/ee3158183f66115467b00977f1bc99c8587f8547

**Pull request closed without merging**
