### PR TITLE
Moved upload files page to main files area

### PR DESCRIPTION
**Pull request by scott1702**
Behat tests will fail until related framework PR is merged - https://github.com/silverstripe/silverstripe-framework/pull/4623

### CODE REVIEW

**Comment by chillu** [comment]
I've merged the other commit and gave travis a kick. Scott, can you please check how they went in an hour or so?

**Comment by chillu** [comment]
Can you please send a pull request to the `framework` changelog (`docs/en/changelogs/4.0.md`) which notes the removal of the `CMSFileAddController` class? Devs might have extended it, so its a noteworthy removal

**Comment by scott1702** [comment]
Can do!

**Comment by tractorcow** [comment]
Fix for the issue at https://github.com/silverstripe/silverstripe-framework/pull/4639

**Comment by tractorcow** [comment]
Tested locally with this in my main.php

```php
unset($_REQUEST['url']);
unset($_GET['url']);
``` 

Seems to work fine. :)

**Pull request merged**
