### PR TITLE
BUG Fix behaviour towards versioned but unstagable records

### PR DESCRIPTION
**Pull request by tractorcow**
Parent issue: https://github.com/silverstripe/silverstripe-versioned/issues/115

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow these won't go green despite the other PRs being merged :(

**Comment by tractorcow** [comment]
hm that test is broken even on 4.0 branch now.

**Comment by tractorcow** [comment]
Ah, it's a regression from an earlier versioned change. :D don't worry the test was bad because it was relying on incorrect rollback behaviour.

**Comment by tractorcow** [comment]
Green @dhensby

**Pull request merged**
