### PR TITLE
BUG Restore SiteTree::canPublish method to resolve incorrect fallback…

### PR DESCRIPTION
**Pull request by tractorcow**
… to SiteTreeExtension

Fixes https://github.com/silverstripe/silverstripe-framework/issues/5625

### CODE REVIEW

**Comment by dhensby** [comment]
tests? :trollface:

**Comment by tractorcow** [comment]
Ok, there are some tests.

**Comment by tractorcow** [comment]
Tests didn't pass though. =(

**Comment by tractorcow** [comment]
It looks like the tests were failing anyway.

**Pull request merged**
