### PR TITLE
BUG Fix localisation issues in CMS

### PR DESCRIPTION
**Pull request by tractorcow**
This should resolve the majority of behat regressions caused within the last release.

Should fix most issues in this pull request only, but remainder of regressions fixed with https://github.com/silverstripe/silverstripe-framework/pull/6365

### CODE REVIEW

**Comment by tractorcow** [comment]
Putting impact/high back; We need to get behat tests green for current pull requests.

**Comment by kinglozzer** [comment]
silverstripe/silverstripe-framework#6365 merged, restarting behat...

**Comment by kinglozzer** [comment]
Hmm, we still have [a failure](https://travis-ci.org/silverstripe/silverstripe-cms/jobs/181486238#L575). Perhaps it’s failing the `Then I should not see a ".ss-uploadfield-files .ss-uploadfield-item" element` check from the previous scenario? I can’t see why else it would fail immediately before even trying anything!

**Comment by tractorcow** [comment]
It seems to be from this.

image

Wish we had artifacts working...

**Comment by dhensby** [comment]
Wish no more!

**Comment by kinglozzer** [comment]
Huh? Aren’t behat tests still failing? @dhensby

**Comment by dhensby** [comment]
> Edit: Actually I guess this is a step closer, so that probably didn’t need to block this PR :)

yep

**Pull request merged**
