### PR TITLE
FIX Regression issue UI URLSegment buttons

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Parent issue
- https://github.com/silverstripe/silverstripe-cms/issues/2885

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Not doing a proper review, just looking at this in passing - but does this mean we can't have those icons on any buttons anywhere anymore? That seems like a regression that goes deeper than this PR would resolve.

**Review by maxime-rainville — APPROVED** [review]
Looks good. Tested in chrome and Firefox

**Comment by maxime-rainville** [comment]
> Not doing a proper review, just looking at this in passing - but does this mean we can't have those icons on any buttons anywhere anymore? That seems like a regression that goes deeper than this PR would resolve.

The icon still works fine on all the other buttons. Those split buttons were never meant to have icons and have some weird padding applied to them which was cause this strange behaviour.

Looking at the pattern lib, the you can still apply icons to them just fine.

https://silverstripe.github.io/silverstripe-pattern-lib/?path=/docs/admin-buttons-button--documentation

**Comment by GuySartorelli** [comment]
The pattern library is for react components. The template (which is what this PR affects) is for the entwine implementation, I believe.

**Pull request merged**
