### PR TITLE
FIX canonical tag on VirtualPage

### PR DESCRIPTION
**Pull request by xini**
The canonical tag should be a `link` tag not `meta`, see https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks @xini. Did you check if there's an existing unit test we can update as well or there's nothing covering this at this stage for the VirtualPage or any page in general?

**Comment by xini** [comment]
@michalkleiner I haven't found any tests covering this, no.

**Comment by michalkleiner** [comment]
Thanks @xini, yeah, it looks like there's nothing current. There's a test class for the whole VirtualPage, so I think we could take a subset from https://github.com/silverstripe/silverstripe-cms/blob/4/tests/php/Model/SiteTreeTest.php#L1389 and add it into a new test in https://github.com/silverstripe/silverstripe-cms/blob/4/tests/php/Model/VirtualPageTest.php#L19, potentially testing other expected headers as well, such as that the value of the canonical should point to the referenced page.

Do you think you can look into that, please?

**Review by dhensby — APPROVED** [review]
This change looks good. Whilst a test would be nice, we shouldn't block a fix waiting for a test if there is currently no test coverage anyway.

**Comment by michalkleiner** [comment]
I was of two minds on that too, @dhensby. Let's give @xini a chance if he wants to/can add the test, and merge without it if not.

**Comment by dhensby** [comment]
Thanks for the test @xini - I think there's some linting (tabs/spaces being mixed) to sort out in the test

**Comment by xini** [comment]
@dhensby I noticed, thanks. Fixed now.

**Comment by michalkleiner** [comment]
Thanks @xini, great work. Test failure is unrelated.

**Comment by xini** [comment]
Thanks @michalkleiner

**Pull request merged**
