### PR TITLE
Removed ErrorPage

### PR DESCRIPTION
**Pull request by jonom**
Removed ErrorPage class and references so it can be split off in to a separate module.

May require supporting Framework PR for tests to pass. https://github.com/silverstripe/silverstripe-framework/pull/7017

Not sure if there is any point removing the translations? Does that need to happen in Transifex?

Related RFC: https://github.com/silverstripe/silverstripe-framework/issues/4149

### CODE REVIEW

**Comment by flamerohr** [comment]
Amazing effort, only test failing is a behat test which targets an ErrorPage :)

**Comment by tractorcow** [comment]
Hi @jonom in order to get this over the line before beta1, I think we will need an errorpage module (suggest `silverstripe/errorpage`) and add this to the installer at the same time as merging this. Do you feel like putting this together?

**Comment by tractorcow** [comment]
Blank repo with necessary permissions setup at https://github.com/silverstripe/silverstripe-errorpage :D

**Comment by chillu** [comment]
Needs a rebase

**Comment by jonom** [comment]
@chillu rebased. Just a couple of behat tests failing - same ones as in the Framework PR so must be unrelated.

**Comment by jonom** [comment]
Thanks for the merge!

**Pull request merged**
