### PR TITLE
FIX: Fixes #2110 added default Title value for saved pages.

### LINKED ISSUE #2110: You shouldn't be able to save a page without page name and navigation label
It feels like a page should always have a name and navigation label, possibly it should be a required field—or at least get a warning. This would prevent empty items in the tree, and unintentional empty fields.

If they don't want the page to be displayed in the template devs should be able to accommodate that scenario.

Note an empty item in the tree:
image

# Related PR
* [ ] https://github.com/silverstripe/silverstripe-cms/pull/2366

### PR DESCRIPTION
**Pull request by ttunua**
Closes #2110

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Thanks for the PR @ttunua . It looks like this is still blocked a little by ongoing discussion in the attached issue. I'm not sure a consensus has been reached.

Additionally there's a failing test and some linting violations that will need to be corrected. I'll try to spur on some discussion on the related issue for you.

**Comment by ttunua** [comment]
added some fixes, please review when you can

**Comment by ScopeyNZ** [comment]
Thanks @ttunua it's looking good. There's still some debate (I think) about whether it should be "New [page type]" or "Untitled [page type]". We'll see what's decided before we merge anything.

Thanks for the contribution!

**Comment by ScopeyNZ** [comment]
I think we can merge this if we change the default to "Untitled". That seems to be winning the vote in the attached issue.

**Pull request merged**
