### PR TITLE
FIX Unsaved SiteTree records now return an empty list for DependentPages

### LINKED ISSUE #2343: Updated DependentPages logic doesn't handle UnsavedRelationLists
**Version: 4.3.x-dev**

After #2276 was merged, we have a set of "alterDataQuery" calls on relationship lists. If the object is not yet written and we call `getCMSFields()`, we can get an error because you can't alter a query on an UnsavedRelationList.

Example:

```php
$page = new SiteTree();
$page->getCMSFields();
```

This example exists in versioned-admin, and broke in a test recently:

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
.....................E.....                                       27 / 27 (100%)
Time: 11.76 seconds, Memory: 118.00MB
There was 1 error:
1) SilverStripe\VersionedAdmin\Tests\Forms\DataObjectVersionFormFactoryTest::testSiteTreeMetaFieldsHaveNoRightTitle
BadMethodCallException: Object->__call(): the method 'alterDataQuery' does not exist on 'SilverStripe\ORM\UnsavedRelationList'
/home/travis/build/silverstripe/silverstripe-versioned-admin/vendor/silverstripe/framework/src/Core/CustomMethods.php:54
/home/travis/build/silverstripe/silverstripe-versioned-admin/vendor/silverstripe/cms/code/Model/SiteTree.php:1794
/home/travis/build/silverstripe/silverstripe-versioned-admin/vendor/silverstripe/cms/code/Model/SiteTree.php:1889
/home/travis/build/silverstripe/silverstripe-versioned-admin/src/Forms/DataObjectVersionFormFactory.php:97
/home/travis/build/silverstripe/silverstripe-versioned-admin/src/Forms/DataObjectVersionFormFactory.php:49
/home/travis/build/silverstripe/silverstripe-versioned-admin/tests/Forms/DataObjectVersionFormFactoryTest.php:120
/home/travis/build/silverstripe/silverstripe-versioned-admin/vendor/phpunit/phpunit/phpunit:52
```

Relevant code from the test:

```php
# DataObjectVersionFormFactoryTest
        $context = [
            'Record' => new SiteTree(),
        ];
        $form = $this->factory->getForm($this->controller, 'some_form', $context);
```

```php
# DataObjectVersionFormFactory
        $record = $context['Record'];
        /** @var FieldList $fields */
        $fields = $record->getCMSFields();
```

```php
# SiteTree
        // Virtual pages
        if ($includeVirtuals) {
            $virtuals = $this->VirtualPages()
                ->alterDataQuery(function ($query) {
                    $query->selectField("'Virtual page'", "DependentLinkType");
                });
```

If `$this->VirtualPages() instanceof UnsavedRelationList` we should not alter the query.

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #2343

### CODE REVIEW

**Comment by kinglozzer** [comment]
This change makes sense to me, looks like the test failures are related though

**Comment by robbieaverill** [comment]
Yeah- I think we resolved similar ones in 4 by merging up. Will check in a bit

**Comment by robbieaverill** [comment]
Tests fixed in 29a22bcb

**Comment by ScopeyNZ** [comment]
I've just reran the tests again after the fix in #2348 🤞

**Pull request merged**
