### PR TITLE
MINOR: Remove trailing whitespace

### PR DESCRIPTION
**Pull request by sminnee**
Ran this command on all files:

    find . -not \( -name .svn -prune -o -name .git -prune \) -type f | grep -vE .\(gif\|png\|jpg\) | xargs perl -pi -e 's/ +$//'

The main benefit of this is so that authors who make use of
.editorconfig don't end up with whitespace changes in their PRs.

See also: https://github.com/silverstripe/silverstripe-framework/pull/4888

### CODE REVIEW

**Comment by tractorcow** [comment]
You need to fix ContentControllerTest to expect the trailing newline (as it was added to the template).

You can also trim the newline from the result as an alternative, to make the test newline agnostic. :)

**Comment by sminnee** [comment]
OK I've broken out the non-whitespace changes into a separate commit, for clarity, and I've opted for ignoring the whitespace rather than allowing for it, as it's not material to the code being tested.

**Comment by tractorcow** [comment]
There's a behat test failure; Can you test it locally to see if it's real?

**Comment by tractorcow** [comment]
image

**Comment by tractorcow** [comment]
Possibly related to the 3 branch changes: https://github.com/silverstripe/silverstripe-framework/issues/4895

**Comment by sminnee** [comment]
It looks like upstream changes have fixed the failure; should be ready for merge now

**Pull request merged**
