### PR TITLE
Fix 'Insert links into a page' test

### PR DESCRIPTION
**Pull request by lukereative**
Fix tests for https://github.com/silverstripe/silverstripe-admin/pull/637 (they won't pass till this is merged in though)

### CODE REVIEW

**Comment by robbieaverill** [comment]
The tests are failing =/

**Comment by lukereative** [comment]
They won't pass until the mentioned PR is merged in (it's dependent on those changes)

**Comment by ScopeyNZ** [comment]
> They won't pass until the mentioned PR is merged in (it's dependent on those changes)

Huh? It's a test on the PR branch so it runs behat with your updated changes? If this PR is supposed to fix behat I'm not sure that it's working correctly...

**Comment by lukereative** [comment]
@robbieaverill These test changes nor the tests in the branch will pass until they are both merged in, as they are dependent on each other – this test looks for a different capitalisation which is only in the other branch.

**Comment by robbieaverill** [comment]
Man I thought we'd gotten away from this kind of test coupling. Ok well I guess merge both then and make follow up PRs if they don't pass afterwards =/

**Pull request merged**
