### PR TITLE
MNT Travis shared config

### PR DESCRIPTION
**Pull request by emteknetnz**

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Hey @emteknetnz. You've raised a lot of these PRs. It would probably save a bunch of time to just create branches, and self-merge when the tests go green rather than have a PR for this. I'm not really sure there's any value in requiring someone to look over every single one of these PRs.

Often the core contributing team does changes like this without PR anyway, so I think it's fine for you to do this.

**Comment by emteknetnz** [comment]
At this stage the loose plan is to just follow the standard process and have someone at this end look at them before merging, though we may end up doing what you suggest and just self-merge them depending how things go

Feel free to just ignore these PR's =)

**Comment by ScopeyNZ** [comment]
I wish it was easier: 

image

**Review by Cheddam — COMMENTED** [review]
Just a couple of questions:

- You've added duplicates of two existing images to `client/src/images/images` - was this intended?
- Was `client/dist/js/vendor.js` supposed to be removed? Looks like maybe it was a broken duplicate or something?

**Comment by emteknetnz** [comment]
> You've added duplicates of two existing images to client/src/images/images - was this intended?
Yes.  The shared config will delete the client/dist folder, rebuild everything and check the diff.  Previously those images didn't live in the src folder, only the dist folder, so on rebuild they no longer existed in the dist folder.

> Was client/dist/js/vendor.js supposed to be removed? Looks like maybe it was a broken duplicate or something?
Yes.  It's a very old dist file that's not actually used - last updated 4 years ago.

**Comment by Cheddam** [comment]
> Previously those images didn't live in the src folder, only the dist folder, so on rebuild they no longer existed in the dist folder.

Weirdly I see two copies of them in the src folder now, one set in a nested `images` folder, which is what I was trying to point out (poorly):

- https://github.com/creative-commoners/silverstripe-cms/blob/pulls/4.7/travis-shared/client/src/images/alert.gif
- https://github.com/creative-commoners/silverstripe-cms/blob/pulls/4.7/travis-shared/client/src/images/images/alert.gif
- https://github.com/creative-commoners/silverstripe-cms/blob/pulls/4.7/travis-shared/client/src/images/loading.gif
- https://github.com/creative-commoners/silverstripe-cms/blob/pulls/4.7/travis-shared/client/src/images/images/loading.gif

**Comment by emteknetnz** [comment]
Oh right gotcha.  Have deleted the images/images versions.

**Pull request merged**
