### PR TITLE
Add test to make sure you can create a page under another page

### PR DESCRIPTION
**Pull request by bergice**

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
This was closed without merging? Did I miss something? I don't think this needed to go into the hotfix branch for 4.3.0?

**Comment by ScopeyNZ** [comment]
I'm going to re-open this with the base branch set back to 4.3. I couldn't see this change in the 4.3.0 tag.

**Comment by ScopeyNZ** [comment]
Also I'm just going to merge it 😛

**Comment by robbieaverill** [comment]
GitHub auto closes pull requests against a branch that gets deleted (4.3.0 in this case)

**Pull request merged**
